# Generated by Django 4.2.10 on 2024-04-10 13:37

from django.db import migrations, models
import django.db.models.deletion
import pereval.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('height', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('', ''), ('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='', max_length=2)),
                ('summer', models.CharField(choices=[('', ''), ('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='', max_length=2)),
                ('autumn', models.CharField(choices=[('', ''), ('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='', max_length=2)),
                ('spring', models.CharField(choices=[('', ''), ('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='', max_length=2)),
            ],
            options={
                'verbose_name': 'Категория трудности',
                'verbose_name_plural': 'Категории трудности',
            },
        ),
        migrations.CreateModel(
            name='PassUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='Email адрес')),
                ('fam', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('otc', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('beauty_title', models.CharField(max_length=250, verbose_name='Красивое название')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('other_titles', models.CharField(max_length=250, verbose_name='Дополнительное название')),
                ('connect', models.CharField(blank=True, null=True, verbose_name='Какие объекты на местности соединяет данный перевал')),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], verbose_name='Статус')),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.passuser')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('data', models.ImageField(blank=True, null=True, upload_to=pereval.util.get_path_upload_photo)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pereval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.passes')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
